### ISSUE TITLE
[2] Test Ingest

### ISSUE THREAD

**Issue by crisr15** [notch8/utk-hyku#133]
Test imports and confirm they are coming in properly. 

We may sample data from client.

Sample files: https://assaydepot.slack.com/archives/C0396LSM06P/p1666654210407659

**Comment by ShanaLMoore** [comment]
Tested with the following details but this will need to be redone once #131 is complete: 

metadata profile: https://dc.utk-hyku-staging.notch8.cloud/profiles/14?locale=en
sample file: [shaina_boydcs_with_files-small.csv](https://github.com/scientist-softserv/utk-hyku/files/9872710/shaina_boydcs_with_files-small.csv)
importer: https://dc.utk-hyku-staging.notch8.cloud/importers/41?locale=en#work-entries

Advised client on how their spreadsheets need to change: https://assaydepot.slack.com/archives/C0396LSM06P/p1666737305132069?thread_ts=1666654210.407659&cid=C0396LSM06P

**Comment by kirkkwang** [comment]
@ShanaLMoore

LaRita and I ran the import with the exact CSV attached, but it looks like it didn't overwrite your Works and instead amended it (incorrectly) so we got something like this.

![Image](https://user-images.githubusercontent.com/19597776/200892569-c4899556-0b71-4031-a53e-855bce03451a.png)

From my understanding, an Attachment should only ever have 1 FileSet is that correct?

Also getting these errors in Sidekiq


![Image](https://user-images.githubusercontent.com/19597776/200893641-f5db4d47-19c5-4207-ae88-30b2184b3567.png)

**Comment by kirkkwang** [comment]
After changing the identifiers, we got a successful import.

https://dc.utk-hyku-staging.notch8.cloud/concern/images/78f93bb9-ecc5-46bb-9943-9422a317aabd?locale=en

**Comment by kirkkwang** [comment]
@crisr15 

Was there talks of making the MODS and PRESERVATION attachments private?  Is so the CSV needs to have a `visibility` header and the files they wish to be private need to be `restricted`.

I did that test and on the Work level, the visibility gets set.

![Image](https://user-images.githubusercontent.com/19597776/200901580-3c634c99-d8b1-4e54-912e-a81468b9cc79.png)

However, the FileSet did not get the visibility of its parent.

![Image](https://user-images.githubusercontent.com/19597776/200901763-a8603cc0-7318-4c1d-a8f3-4aca64262ea9.png)

We think this is because the `Hyrax::VisibilityPropagator` was acting funky.  @laritakr thinks this is because its receiving an Allinson Flex type object and doesn't know what to do with it.

https://github.com/samvera/hyrax/blob/main/app/services/hyrax/visibility_propagator.rb#L11-L20

**Comment by laritakr** [comment]
Updated ticket #136 for above issue, and created #180 related to the fits error we are also seeing. 

Still need a ticket related to the issue where repeating an ingest incorrectly amended the filesets.

**Comment by kirkkwang** [comment]
Created #181 related to the reimport issue
