### ISSUE TITLE
[3]Bug: Confirm that overrides are working - check that Decorator Files are loaded

### ISSUE THREAD

**Issue by crisr15** [notch8/utk-hyku#143]
## SUMMARY

While working on #80 @laritakr noticed that [some decorator files](https://gitlab.com/notch8/utk-hyku/-/blob/main/app/helpers/blacklight/catalog_helper_behavior_decorator.rb) were not being loaded. 

We need to double check that these files are being loaded and overriding the intended methods. If not, let's: 
1) try to resolve the issue OR
2) switch to a different override method such as class_eval or module_eval

We believe the issue was introduced by Allinson Flex. 

- [ ] Start by investigating the included modules from [here](https://gitlab.com/notch8/utk-hyku/-/blob/main/app/helpers/hyrax_helper.rb#L5-9)
- [ ] Search repo for Decorator
- [ ] Verify the files are being loaded and used

## Acceptance Criteria
- [ ] The app should use the decorator or overridden files/methods if they exist

## NOTES: 
https://playbook-staging.notch8.com/en/dev/ruby/decorators-and-class-eval

**Comment by ShanaLMoore** [comment]
ref a workaround: https://gitlab.com/notch8/utk-hyku/-/blob/main/app/helpers/hyrax/work_form_helper_decorator.rb

**Comment by ShanaLMoore** [comment]
config/application.rb

```
Dir.glob(Rails.root.join("app/**/*_decorator*.rb")).sort => 

["/app/samvera/hyrax-webapp/app/controllers/allinson_flex/profiles_controller_decorator.rb",
 "/app/samvera/hyrax-webapp/app/controllers/bulkrax/importers_controller_decorator.rb",
 "/app/samvera/hyrax-webapp/app/controllers/hyrax/my/works_controller_decorator.rb",
 "/app/samvera/hyrax-webapp/app/forms/hyrax/forms/collection_form_decorator.rb",
 "/app/samvera/hyrax-webapp/app/helpers/hyrax/hyrax_helper_behavior_decorator.rb",
 "/app/samvera/hyrax-webapp/app/helpers/hyrax/work_form_helper_decorator.rb",
 "/app/samvera/hyrax-webapp/app/jobs/create_derivatives_job_decorator.rb",
 "/app/samvera/hyrax-webapp/app/models/admin_set_decorator.rb",
 "/app/samvera/hyrax-webapp/app/models/concerns/bulkrax/import_behavior_decorato
r.rb",
 "/app/samvera/hyrax-webapp/app/models/concerns/hyrax/solr_document_behavior_dec
orator.rb",
 "/app/samvera/hyrax-webapp/app/presenters/hyrax/iiif_manifest_presenter_decorat
or.rb",
 "/app/samvera/hyrax-webapp/app/search_builders/hyrax/filter_by_type_decorator.r
b",
 "/app/samvera/hyrax-webapp/app/services/allinson_flex/dynamic_schema_service_de
corator.rb",
 "/app/samvera/hyrax-webapp/app/services/hyrax/manifest_builder_service_decorato
r.rb"]
```

**Comment by ShanaLMoore** [comment]
- [ ] "/app/samvera/hyrax-webapp/app/controllers/allinson_flex/profiles_controller_decorator.rb",
- [ ]  "/app/samvera/hyrax-webapp/app/controllers/bulkrax/importers_controller_decorator.rb",
- [ ]  "/app/samvera/hyrax-webapp/app/controllers/hyrax/my/works_controller_decorator.rb",
- [x]  "/app/samvera/hyrax-webapp/app/forms/hyrax/forms/collection_form_decorator.rb",
- [x]  "/app/samvera/hyrax-webapp/app/helpers/hyrax/hyrax_helper_behavior_decorator.rb",
  - converted to decorator pattern ✅ 
- [x]  "/app/samvera/hyrax-webapp/app/helpers/hyrax/work_form_helper_decorator.rb",
  - this was being included in hyrax helper instead of using prepend. converted ✅ 
- [x]  "/app/samvera/hyrax-webapp/app/jobs/create_derivatives_job_decorator.rb",
- [x]  "/app/samvera/hyrax-webapp/app/models/admin_set_decorator.rb",
- [ ]  "/app/samvera/hyrax-webapp/app/models/concerns/bulkrax/import_behavior_decorator.rb",
- [ ]  "/app/samvera/hyrax-webapp/app/models/concerns/hyrax/solr_document_behavior_decorator.rb",
- [ ]  "/app/samvera/hyrax-webapp/app/presenters/hyrax/iiif_manifest_presenter_decorator.rb",
- [x]  **"/app/samvera/hyrax-webapp/app/search_builders/hyrax/filter_by_type_decorator.rb",**
  - converted from module_eval to decorator pattern and the pry does not stop, even though this is listed in the dir.glob
  - Hyrax::FilterByType.ancestors => [Hyrax::FilterByTypeDecorator, Hyrax::FilterByType] 🤔 
- [ ]  "/app/samvera/hyrax-webapp/app/services/allinson_flex/dynamic_schema_service_decorator.rb",
- [ ]  "/app/samvera/hyrax-webapp/app/services/hyrax/manifest_builder_service_decorator.rb"

**Comment by ShanaLMoore** [comment]
After time-boxing debugging and pairing with Jeremy about different options, to fix this we can consider: 

1) Alter active support concern to allow it to accept multiple included block. "Soft serve decorator" should behave like active support concern but allow it to take multiple included blocks. Make a macro for it. 
- is there a reason why active support won't allow multiple included blocks? 

For UTK's concern we will likely not spend time to implement this. For module overrides we will need to use module_eval. 

**Note**: module_evals looses access to super.
