### ISSUE TITLE
Spike: UTK Importer Issues

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#322]

**Comment by markpbaggett** [comment]
Hello, in our app, we have a bug where Bulkrax imports fail silently. As far as I can tell, this only happens on Works.  In our instance, you can see this in [Importer 84](https://dc.utk-hyku-production.notch8.cloud/importers/84?locale=en).  When you visit the importer page, you see no evidence of import errors, but if you crawl the importer you'll see Works that failed to import:

![roth:201 ](https://user-images.githubusercontent.com/2692416/216502863-943425c2-bba2-4da7-adb7-8d1331af7950.png)

The error messages seem to be like the above or `LDP::HTTPError`.

![roth:698 ](https://user-images.githubusercontent.com/2692416/216502990-b8e25779-ef6a-4203-ba45-4b5c68869480.png)


The error makes it so that you cannot attach attachments / filesets. In order to fix this, you have to delete the known items, reimport them, delete them again, and then reimport.  This last reimport seems to fix.

If you rerun the importer with failed imports as is, the problem gets worse.  The failed import then gets marked as Complete, but you can't attach things to it.



My hypothesis is that the create relationships job isn't completing.

Also, the import jobs seem to be marked as pending rather than completed initially. Rerunning will mark as complete, but the silent failures are then marked as Complete even though they are still failures.  Attached is an example sheet in case it's helpful:

[roth_full_with_collections.csv](https://github.com/scientist-softserv/utk-hyku/files/10575198/roth_full_with_collections.csv)

**Comment by ShanaLMoore** [comment]
Treating this ticket as a spike first, to determine the problem. This ticket can be closed once and implementation ticket is created. #323

**Comment by ShanaLMoore** [comment]
Shana and Mark to meet via slack huddle at 11AM PST today, to clarify the problems.

**Comment by ShanaLMoore** [comment]
Solve why the error entries download button doesn't show up when there are some failed entries. 

Solve pending status issue reported in Bulkrax: https://github.com/samvera-labs/bulkrax/issues/459

Look into error messages like LDP::Gone and ActiveFedora::ObjectNotFound. Re running will show that it is complete, but it will not allow attachments/relationships. Mark has to make sure the works are deleted (twice) before re add and re attaching. 

delete twice means he is uploading a csv w the delete column marked as true. delete twice == Delete add, delete add. 

Mark currently has a workaround so this is more of a frustration in the workflow vs a blocker.

**Comment by ShanaLMoore** [comment]
I've handed this issue over to Rob #323 , who will try to debug and resolve in between his meetings + share the results with me soon.
