### ISSUE TITLE
Conditional Derivatives: Inject module into registered  to override  function

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#343]
# Summary 
See https://github.com/scientist-softserv/utk-hyku/issues/342 for more context and discussion:

See https://github.com/samvera-labs/bulkrax/issues/760 for a more robust solution based on conversations.

## [DRAFT] Todo Items 

  - Create a `module` that we `prepend` to each of the plugins registered in `Hyrax::DerivativeService.services`
  - Document/determine how we discern when we do not want generate derivatives
  - Define `#valid?` to use the above defined logic to return true or false based on the given file_set's "properties"
  - Will need to alter how we run the text extraction; as it assumes we extract text from a generated derivative file.

- [x] #371
- [x] #374
- [ ] #372
  - as outlined in https://github.com/samvera-labs/bulkrax/pull/761
- [x] #378
- [ ] #373
- [x] #375
- [ ] TBD: Integration work with IIIF Print configuration

# Acceptance Criteria

- [ ] A user should be able to import and use their own derivatives
- [ ] If a user is importing derivatives, the application should not override/recreate them

# Screenshots or Video

# Testing Instructions

# Notes

Sample file: 

[humbug_with_attachments.csv](https://github.com/scientist-softserv/utk-hyku/files/10786250/humbug_with_attachments.csv)

Slack Convo: https://assaydepot.slack.com/archives/C0396LSM06P/p1676387122559459

**Comment by ShanaLMoore** [comment]
Mark's sample file for Books: 



[humbug_with_attachments.csv](https://github.com/scientist-softserv/utk-hyku/files/10786248/humbug_with_attachments.csv)

**Comment by ShanaLMoore** [comment]
Q: Is this ready for QA? Can we update the testing instructions if so...

A: Per Jeremy -- 

The behavior is a no operational change at this point.  And the unit tests cover the behavior.
As Kirk and I explored this ticket, there are several questions that come up but mostly in relation to IIIF Print.
As written the first three bullet points are roughly set, but the 4th bullet point requires IIIF Print.

So in other words, the pull request relates to the ticket but does not close the ticket as I had initially thought.
Further, to write testing instructions will require a more involved conversation with Mark about “what do we mean by derivatives”.  But before that conversation we need to work through use cases to present decision-making to Mark.
Part of this relates to what is the nature of the file_set but also the related file_sets for the parent work (e.g. you uploaded an HOCR and TIFF…do we run OCR on this?  What about text extraction?)

moving it back to in-development because there’s more work to be done to deliver on the specifics.

**Comment by jeremyf** [comment]
In the current implementation when a `FileSet` has an rdf\_type that is “IntermediateFile”, we skip all derivative generation processes.  That includes:

1.  Thumbnails
2.  Text extraction
3.  Image resizing
4.  Transcoding time-based media to other formats
5.  Text coordinates file

What we need to understand is when we say skip derivatives, what do we mean?  Skip everything?  Or skip transcoding but continue with thumbnails, text extraction, etc.

**Comment by markpbaggett** [comment]
Hey all, so I'm not sure I totally follow and maybe it'd be good to have a quick huddle next week to make sure you all have the information you need.

In `Image`, we skipped processing on `FileSets` unless the `FileSet` was an instance of `<http://pcdm.org/use#IntermediateFile>`. Therefore, an `Image` with a `FileSet` that was both a `<http://pcdm.org/use#IntermediateFile>` and a `<http://pcdm.org/use#PreservationFile>` still got a thumbnail and other processing.  Also, in `Image`, the `<http://pcdm.org/use#IntermediateFile>` is the FileSet that should be served via UniversalViewer.  The reason for this is that sometimes an `Image` may have a separate `http://pcdm.org/use#PreservationFile` that includes a color target and other things that we don't want to be served but we want to keep around for the sake of preservation.

This same concept exists in a `Book`.  A page of a book may have a `FileSet` that is the `<http://pcdm.org/use#IntermediateFile>` and `<http://pcdm.org/use#PreservationFile>` or it could have these as separate FileSets.  In both cases, only the FileSet with this class `<http://pcdm.org/use#IntermediateFile>` is what is served in the viewer and has associated OCR / HOCR.  

If we're migrating HOCR / OCR, it is associated with the `<http://pcdm.org/use#IntermediateFile>`. In my example where we are migrating OCR and HOCR rather than regenerating, the OCR is an instance of `http://pcdm.org/use#ExtractedText` (nothing else is) and the HOCR is an instance of `http://pcdm.org/file-format-types#HTML` (nothing else is).  These will always be associated with the intermediate file.  

In thinking about this and skipping derivatives, what we wanted initially was to just save processing time for migration by migrating the OCR and HOCR but still generate a thumbnail.  If this seems like the wrong approach, we're open to suggestions. Also, in our current system, we use Cantaloupe and just generate thumbnails.  All other image sizing is done on demand rather than pre-cached.

Another important thing to note:  we want to generate OCR  and HOCR in system after migration (not do it out of system and bring it in).  My initial thinking was that the trigger for determining this would be whether or not a FileSet / Attachment with `http://pcdm.org/use#ExtractedText` or `http://pcdm.org/file-format-types#HTML` was present, but maybe that is overly complicated since the importer would then have to understand all the parts up front in order to know what to do.

Finally, apologies if I'm not following completely or have only made things more confusing. If it helps, I'm happy to have a huddle on Monday.

**Comment by jeremyf** [comment]
> Hey all, so I'm not sure I totally follow and maybe it'd be good to have a quick huddle next week to make sure you all have the information you need.

Agreed.  We need to talk about this to make sure we have a shared understanding of the PCDM data modeling as well as the existing data that will be imported.

In particular, we need to get precise about our shared understanding of `FileSet`.  In Hyrax, a `FileSet` represents one of the “original” files associated with it’s parent work.  Then, as part of processing, Hyrax creates derivatives on the “original” file and associates them to that `FileSet`.  These derivatives include:

-   Thumbnail
-   Extracted text
-   HOCR
-   etc.

The derivatives are downloadable in the Universal Viewer.  The extracted text is added to the FileSet SOLR document for search purposes.  And the thumbnail is used for the `FileSet` show/list page.

In our read of the following we have two problems:

1.  Configuring which derivatives to run.
2.  Associating the provided derivatives with the correct functionality of a `FileSet`.

As we discuss further, we're wondering how vital it is to carry forward the RDF Type property?

**Comment by markpbaggett** [comment]
@jeremyf Thanks for following up.  Just in case it's helpful, I want to provide a little more context. You may already have this all, but I wanted to share just in case you did not.

In our books, images, and videos (maybe other work types too?), we sometimes have two original files.  

For images and pages, there is one that has a Golden Thread target (the preservation image) and one without it.  Here is an example:

* [boydcs:1 pcdmuse:PreservationFile](https://digital.lib.utk.edu/collections/islandora/object/boydcs:1/datastream/PRESERVE/view)
* [boydcs:1 pcdmuse:IntermediateFile](https://digital.lib.utk.edu/collections/islandora/object/boydcs:1/datastream/OBJ/view)

For books and pages, this also MAY exist:

* [utrecord:50 pcdmuse:PreservationFile](https://digital.lib.utk.edu/collections/islandora/object/utrecord:50/datastream/PRESERVE/view)
*.[utrecord:50 pcdmuse:IntermediateFile](https://digital.lib.utk.edu/collections/islandora/object/utrecord:50/datastream/OBJ/view) 

For videos, this also MAY exist and when it does the preservation object usually has a totally different duration from the intermediate files because the intermediate file has extra things (intro bumpers / outro bumpers):

* [rfta:8 pcdmuse:PreservationFile](https://digital.lib.utk.edu/collections/islandora/object/rfta:8/datastream/OBJ/view)
* [rfta:8 pcdmuse:IntermediateFile](https://digital.lib.utk.edu/collections/islandora/object/rfta:8/datastream/MP4/view)

When we started testing migrations of images and books, this became a problem (especially with books), because you'd get each of these files in Universal Viewer for every page.  Also, the character coordinates information in our existing OCR / hOCR always relates to the `pcdmuse:IntermediateFile`.

When we explained this and asked how can we only get 1 file per page to appear in the viewer, this model was proposed.  Also, I think some of this came up because there was no way to provide metadata about a file with bulkrax (only filesets). If you're wondering why that matters, we have video with subtitles in multiple languages.  In our current system, that's handled by relating the language to the file and translating it to an IANA value.  You can see an example here in a IIIF manifest for a video that has subtitles in both English and Spanish:

* [manifest](https://digital.lib.utk.edu/assemble/manifest/rfta/165)
* [manifest in a video player](https://samvera-labs.github.io/clover-iiif/?iiif-content=https://digital.lib.utk.edu/assemble/manifest/rfta/165)

Hopefully, this provides a little more context about how we got here going back for Spring and Summer of 2022.  We recognize this is a departure from PCDM, but we were just trying to find middle ground between our needs and what Hyku and Bulkrax could do.  We are open to changing whatever needs to be changed in order to unblock migration and get into production as long as it doesn't make it too difficult to get our data back out and into something else if we were to go another direction at some point.

Let me know if you have any other questions that I could provide answers to before tomorrow's meeting.

**Comment by markpbaggett** [comment]
In addition to the above, I thought I might reference this old [work types document](https://utk-future-dc-worktypes.readthedocs.io/en/latest/index.html) from last summer in case it's useful to understand the files we have associated with each work type. Please note that the document here was not meant to be prescriptive but instead helpful in understanding what exists and decisions we need to make about migrating them.

* This page describes [Books and Pages](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/6_books_and_pages.html).
* This page describes [Images](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/2_image.html).
* This page describes [Videos](https://utk-future-dc-worktypes.readthedocs.io/en/latest/contents/3_video.html).

Also, [this document](https://utk-dc-content-models.readthedocs.io/en/latest/index.html) is much older and describes data from our current system with no real thoughts about a future system.

Apologies if all of this is just noise; I just want to make sure everyone has some docs about what exists and how we ended up in this "Frankensteinian" data model.

**Comment by markpbaggett** [comment]
@ShanaLMoore, @jeremyf, @laritakr,

I thought more about what I think is being asked here, and I tried to come up with a list of needs / user stories that we need to be able to do.  These are the needs that I think are mostly responsible for the existing data model.  If we're able to accomplish the things listed below in some way and answer the questions here, I think we can change the data model  in whatever way that will make things "more standard". Please know that what we have now was never meant to be prescriptive but instead help us answer the things below:

**Needs**

1. For import / migration, how do we express what a file is, how it relates to its work, and other files within the work?
    * Examples:
        1. How can we express that something is an OCR file or an HOCR file?
        2. How can we express which file the OCR file or HOCR file is associated with if a page is represented by a `pcdmuse:PreservationFile` and `pcdmuse:IntermediateFile`?
        3. How do we express whether a subtitle file is in English, Spanish, or Italian if the video it belongs to has all three?
2. For works where a `pcdmuse:PreservationFile` and `pcdmuse:IntermediateFile` exists, how can we ensure that both do not appear in UniversalViewer or the associated manifest (especially for books and compound objects)?
3. For works like in question 2, how do you know which file the imported OCR / HOCR is associated with since their width / height may be different? This is probably not a concern as long as there is a way to define what should appear in the IIIF manifest and UV.
4. For video works with subtitles, how do you know:
    * Which video file the subtitle is associated with if both a `pcdmuse:IntermediateFile` and `pcdmuse:PreservationFile` exists?
    * The language of the subtitle file (especially when more than one language exists)?
5. If we’re asked to perform one of the actions below, how can we do that:
    * Get all “Release Forms” for video works in the repository?
    * Generate a list of video works that do not have a subtitle file in any language?
    * Get all OCR files for pages in books in collection X?
6. For export or if we move works from this system to something else, how do we know the nature of the files, get the specific file, etc.
    * How can we get the path to the HOCR, OCR, preservation object, intermediate file?

Also, if it's helpful for figuring this out, I can write up or point at existing documentation about how we do these things now.

**Comment by jeremyf** [comment]
Based on our <2023-03-14 Tue> conversation, I've added a "Needs Rework" tag.  My intention is to show that we need to rethink how we're approaching this work.

We would continue to have Access Copy and Preservation Copy:

- Can we associate the HOCR with the FileSet that has it’s originating file (e.g. that which we ran OCR on to generate the HOCR)
  - The HOCR does not have metadata associated with it that’s highly useful.  So yes we can.
- And if we export, it would export all of the individual pieces.
- There are curated thumbnails; which can be associated with the FileSet.
  - It can be associated with the FileSet.
- Likewise the translations go with the FileSet for which they are applicable.
- Do we generate a thumbnail when one does not exist?  Yes.  It would be okay to have a placeholder.  This could be a place to expedite generation.
- The transcriptions files have conventional language abbreviations.

**Comment by jeremyf** [comment]
A file set entry will have an original file and one or more derivatives; each type of derivative (e.g. translation, hocr, thumbnail, etc.) would have its own column.  When we import the file set we need to capture that information for later consideration (perhaps in a Bulkrax sidecar file that we’d need to create?).  Perhaps we begin fetching those remote resources.

When we then go to generate derivatives for the FileSet, we would check the sidecar for the existence of a pre-generated derivative.  If it exists, we use that as the file (remote fetch).  If it does not, we run the particular derivative as normal.

One of the challenges is understanding where to best put this.  Is it a IIIF Print responsibility?  Certainly there’s a Bulkrax responsibility.  But the derivatives are, in part, generated in Hyrax (though the DerivativeService can easily be modified and replaced).

My suspicion is that this is a Bulkrax plugin/configured option.

**Comment by laritakr** [comment]
I'm not sure of where to find the file information for the derivatives, but I do agree that it is a bulkrax issue rather than iiif_print. (You might want to do this for cases where you do not have iiif_print, but you wouldn't be doing it without bulkrax)
