### ISSUE TITLE
🦄 Spike: Search Facets

### ISSUE THREAD

**Issue by jillpe** [notch8/utk-hyku#402]
# Summary
To complete the definition of done for #392 we need to estimate and present the options for how to make facets behave the way they suggested [here](https://github.com/scientist-softserv/utk-hyku/issues/392#issuecomment-1531582967). If the lift is manageable for either of the options we will continue with their desired approach. If it is a heavy lift, UTK will get rid of role-terms and forcefully map them to the correct facet. 

2 options that have been mentioned already:
- Getting allinsonflex to support indexing
- Creating an override in the app

<details><summary>Notes from meeting 2023-05-23</summary>
- UTK is very old school, so they work with Solr directly (like writing Solr configs). They don’t think that we need to go to an M3 profile, look at an indexing property, and set things out. We don’t need to have a complex way to be able to have role terms (like author, painter, artist). If this isn’t possible because it was such a huge lift, then UTK would have to get rid of role-terms and just forcefully map them to “creator.”
- We’d have to compare AllinsonFlex vs an override in the app and to see how long each process would take. UTK would like for us to think about the costs per option and consider if they’d prefer dc-like terms instead of these creator role-terms. Meredith may be interested in preserving role terms, but she’s on maternity leave at the moment.
- Perhaps we can make an array of fields of everything we’d want to hold together and shove it into an indexed field.

</details>

# Accepted Criteria
- [ ] Pathways for how to get facets to behave the way UTK would like (#392) have been outlined/estimated

**Comment by jillpe** [comment]
related to #392

**Comment by laritakr** [comment]
## Task List

1. Get the list of fields to facet together
    - in UTK define list of fields to group - config variable? on `shared_work_behavior`?
    - in AllinsonFlex update M3 profile - need to determine what this should look like
2. Define new grouped facet field as facetable
    - in UTK, in `shared_work_behavior`
    - in AllinsonFlex, in `dynamic_schema_service`
 3. Map all creator-type fields into grouped facet field in `generate_solr_document`
     - in UTK, model indexers
     - in AllinsonFlex, in `dynamic_indexer_behavior
4.  config.add_facet_field into catalog_controller 
    - In UTK, in catalog_controller
    - In AllinsonFlex, is there a way to have the dynamic_catalog_behavior pick it up?
5. Reindex works

For Browse All, when a user clicks, they should get paginated results with facets available to narrow down results accordingly.

Note: It would be helpful to keep ticket https://github.com/scientist-softserv/utk-hyku/issues/104 in mind, as this also deals with the issue of grouping together the various creators, but this time in a form. There may be some related work.

## Effort Considerations

It will take a bit longer via AllinsonFlex because: 
- additional complexity in dealing with reading it from the dynamic Schema
- Update AllinsonFlex in Utk
- Need to define what it looks like in the metadata profile
- Possible need to update AllinsonFlexConstructor

## M3 Profile Changes 

1. We want one place per M3 profile, outside of the properties, that defines all grouped facet field names (i.e. `creator_facet_sim` and `something_else_facet_sim`)
    - used for `dynamic_schema_service` and `dynamic_catalog_behavior`
2. We want each property to specify which grouped facet field they belong to if applicable
    - used for `dynamic_indexer_behavior`
3. Ideally these changes can be made without requiring a change to the `allinson_flex_constructor`. 

At the profile level, it would look something like below. It would be possible to pull together the profile-level definitions of all grouped facets by reading every property and saving all grouped facets encountered, but this may make loading the `dynamic_solr_document` complicated and time_consuming.
```
grouped_facet:
  - creator_facet
  - something_else_facet
 ```
At the property level, it would look something like this:
```
architect:
  grouped_facet:
  - creator_facet
artist:
  grouped_facet:
  - creator_facet
 ```
## Estimate

If we say doing it directly into UTK is a 3, AllinsonFlex would probably make it a 5. AllinsonFlex could potentially double the time involved due to
- the unknowns involving the M3 profile
- a potential learning curve re: AllinsonFlex

We are guessing roughly somewhere between 3 days and a week of effort... the lower end if done in UTK directly, and potentially even beyond the higher end depending on what is involved with the AllinsonFlex m3 profile changes.

**Comment by jillpe** [comment]
Notes from Crystal on ranking:
Ranking
* It is an algorithm
  * The fields (i.e. title, description, etc.) that show the search term all have different points associated with it (i.e. title = 1, description = 3)
    * Item with the most points sorts to the top of the results
* We need client to tell us which document should show higher and then we go and search tune using this algorithm
  * Ask to prioritize the terms
  * If they change their metadata fields, tuning will need to happen again
* Lea Ann is knowledgeable on this
