### ISSUE TITLE
🎁 Ability to search for all allinson flex metadata properties in the UV

### ISSUE THREAD

**Issue by ShanaLMoore** [notch8/utk-hyku#460]
# Summary

related: #358 

A user can see all of the allinson flex metadata properties in the UV more information pane, however they currently cannot search for all fields. 

# Acceptance Criteria

- [ ] A user should be able to search for all metadata properties

# Screenshots or Video

# Testing Instructions

- [ ] Create a work. Attach a PDF to it, Wait for the jobs to finish. 
- [ ] Once the child works have been created, edit the parent work and add more values to its metadata.
- [ ] Go back to the parent work's show page/UV. 
- [ ] A user should be able to see and search for all of the metadata. 

# Notes

ADL: https://github.com/scientist-softserv/adventist-dl/blob/main/app/controllers/catalog_controller.rb#L80-L81
UTK: https://github.com/scientist-softserv/utk-hyku/blob/main/app/controllers/catalog_controller.rb#L55-L59

maybe helpful?

https://github.com/samvera-labs/allinson_flex/blob/ab9b353a3034c182218356c9320ebe0b6b952a79/app/models/concerns/allinson_flex/dynamic_solr_document.rb#L24

https://github.com/scientist-softserv/iiif_print/blob/fbe418a98bcdce590fc37401f216876fd4c33ec4/lib/iiif_print.rb#L153
=>
https://github.com/scientist-softserv/iiif_print/blob/fbe418a98bcdce590fc37401f216876fd4c33ec4/lib/iiif_print.rb#L187
=>
https://github.com/scientist-softserv/iiif_print/blob/fbe418a98bcdce590fc37401f216876fd4c33ec4/lib/iiif_print.rb#L214

https://github.com/IU-Libraries-Joint-Development/essi/blob/ce126581bb95e2fab2c53f1dcfb3b2a57c69fa3d/app/services/allinson_flex/dynamic_schema_service.rb#L211-L231

**Comment by ShanaLMoore** [comment]
explored a few query options, but within the context of the catalog controller allinson flex profile is nil 🤔 Putting back for now in case others want to pick it up while I focus on other things.

**Comment by kirkkwang** [comment]
Hmm that's strange, I can take a swing and see if I can find anything

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** At the moment, search in UV only works if the query is all lowercase. This will be fixed in https://github.com/scientist-softserv/iiif_print/pull/268.

tested on:
- parent work pdf: https://qa.utk-hyku-staging.notch8.cloud/concern/generic_works/0908b0fc-7462-455d-a33e-297f61df2599?locale=en
- child attachment: https://qa.utk-hyku-staging.notch8.cloud/concern/parent/0908b0fc-7462-455d-a33e-297f61df2599/attachments/113fccf3-91f1-4217-9c4f-fd0eef62247e

# Metadata that can be searched:

## Child attachment metadata:
- [x] abstract
- [x] duration
- [x] resource type
- [x] title

## Parent work metadata:
- [x] Abstract
- [x] Acquisition Identifier
- [x] Alternative Title
- [x] Archival Collection
- [x] ARK
- [x] Artist
- [x] Associated Name
- [x] Attributed Name
- [x] Author
- [x] Bibliographic Citation
- [x] Client
- [x] Compiler
- [x] Composer
- [x] Contractor
- [x] Contributor
- [x] Coordinates
- [x] Copyright Holder
- [x] Correspondent
- [x] Costume Designer
- [x] Creator
- [x] Date Created
- [x] Date Issued
- [x] Date Other
- [x] Unclassified Machine Readable Date
- [x] Dedicatee
- [x] Depicted
- [x] Designer
- [x] Distributor
- [x] Donor
- [x] Editor
- [x] Editor of Compilation
- [x] Engraver
- [x] Extent
- [x] Form
- [x] Local Form
- [x] Former Owner
- [x] Honoree
- [x] Host Institution
- [x] Illustrator
- [x] Instrumentalist
- [x] Intermediate Provider
- [x] Interviewee
- [x] Interviewer
- [x] Is Part Of
- [x] Issuing Body
- [x] Keyword 
- [x] Language
- [x] License
- [x] Lithographer
- [x] Local Identifier
- [x] Lyricist
- [x] Music Copyist
- [x] Musical Director
- [x] Note
- [x] OCLC Number
- [x] Organizer
- [x] Originator
- [x] Other Version
- [x] Owner
- [x] Performer
- [x] Photographer
- [x] Printer
- [x] Primary Identifier
- [x] Printer of Plates
- [x] Producer
- [x] Production Company
- [x] Provider
- [x] Publication Place
- [x] Publisher
- [x] Repository
- [x] Resource Type
- [x] Restorationist
- [x] Rights Statement
- [x] Set Designer
- [x] Host Item
- [x] Signer
- [x] Spatial Coverage
- [x] Local Spatial Coverage
- [x] Speaker
- [x] Stage Director
- [x] Stage Manager
- [x] Standards Body
- [x] Subject
- [x] Surveyor
- [x] Table of Contents
- [x] Temporal Coverage
- [x] Title
- [x] Translator
- [x] Local Artist
- [x] Local Associated Name
- [x] Local Attributed Name
- [x] Local Author
- [x] Local Client
- [x] Local Compiler
- [x] Local Composer
- [x] Local Contractor
- [x] Local Contributor
- [x] Local Copyright Holder
- [x] Local Correspondent
- [x] Local Costume Designer
- [x] Local Creator
- [x] Local Dedicatee
- [x] Local Depicted
- [x] Local Designer
- [x] Local Distributor
- [x] Local Donor
- [x] Local Editor
- [x] Local Editor of Compilation
- [x] Local Engraver
- [x] Local Former Owner
- [x] Local Honoree
- [x] Local Host Institution
- [x] Local Illustrator
- [x] Local Instrumentalist
- [x] Local Interviewee
- [x] Local Interviewer
- [x] Local Issuing Body
- [x] Local Lithographer
- [x] Local Lyricist
- [x] Local Music Copyist
- [x] Local Musical Director
- [x] Local Organizer
- [x] Local Originator
- [x] Local Owner
- [x] Local Performer
- [x] Local Photographer
- [x] Local Publication Place
- [x] Local Printer
- [x] Local Printer of Plates
- [x] Local Producer
- [x] Local Production Company
- [x] Local Restorationist
- [x] Local Set Designer
- [x] Local Signer
- [x] Local Speaker
- [x] Local Stage Director
- [x] Local Stage Manager
- [x] Local Standards Body
- [x] Local Surveyor
- [x] Local Translator
- [x] Local Videographer
- [x] Local Witness
- [x] Videographer
- [x] Witness

**Comment by DiemBTran** [comment]
closing as internal issue
