### ISSUE TITLE
hero

### ISSUE THREAD

**Issue by orangewolf** [notch8/utk-hyku#58]
# Summary
update the home page hero area per the figma wire frames for the dc tenant.

# Acceptance Criteria

- [ ] the hero area is changed to look like the screenshot below

# Screenshots or Video
ref: https://www.figma.com/file/3JjoRJYmCrfoAcWhHu2Br4/UTK?node-id=388%3A789

![Image](https://user-images.githubusercontent.com/29311858/202289484-fc6f7005-abab-49b1-b5b6-deae21150680.png)

**Comment by AKFosterDev** [comment]
PR ready for review https://github.com/scientist-softserv/utk-hyku/pull/122

## Screenshots
The number of collections and works have been hard coded for these screenshots to show the functionality. Commit reverts this back to being dynamically populated.

### XL Screen
![xl 1900px](https://user-images.githubusercontent.com/39319859/200443715-9ab8626b-fadb-40b3-8bb5-8cba5d0f22c4.JPG)

### LG Screen
![lg 1200px](https://user-images.githubusercontent.com/39319859/200443755-6618403f-da53-4e91-a26a-1a5a882a0fff.JPG)

### MD Screen
![md 991px](https://user-images.githubusercontent.com/39319859/200443785-f472464d-f4ab-40a8-81ae-910b399efbcc.JPG)

### SM Screen
![sm 603px](https://user-images.githubusercontent.com/39319859/200443816-47564ca9-a95f-48ca-982d-fe0a528fffd6.JPG)

### Dropdown w/hover
![dropdown w hover](https://user-images.githubusercontent.com/39319859/200443851-fc5aae48-0ef3-44e6-9516-03dc2f4d6d8d.JPG)

**Comment by ShanaLMoore** [comment]
QA: 

**NOTE - the user must switch the appearance to use the DC theme, in order to see the above changes**

cc @AKFosterDev 

This looks good but are there any additional steps I should take to QA this work? I switched to use the DC theme. Should I be seeing a logo instead of hyku in the top corner?
- Amanda will upload the logo and hero image in staging, via the admin dashboard. 

I am also not seeing "all of digital collections" in the drop down. 


When I click libraries it takes me to another site. Is that intentional?


And just curious, how does the user set the hero image?




![Image](https://user-images.githubusercontent.com/10081604/201377682-281c2a89-394a-44e0-a2f1-655f211ff7a2.png)

**Comment by AKFosterDev** [comment]
I am also not seeing "all of digital collections" in the drop down.
- Labels added through the dashboard

When I click libraries it takes me to another site. Is that intentional?
- This links out to the same link that's live on their site.

And just curious, how does the user set the hero image?
- Hero image uploaded to staging site through the dashboard

![Screenshot 2022-11-11 at 8 20 40 AM](https://user-images.githubusercontent.com/39319859/201384887-a2527aee-856b-4e8b-997f-bf379cb8cabf.JPG)

![Screenshot 2022-11-11 at 8 20 48 AM](https://user-images.githubusercontent.com/39319859/201384914-aa22fd6f-6bad-46d3-a4e5-b99a22c07f47.JPG)

**Comment by ShanaLMoore** [comment]
@AKFosterDev When I click to search I am getting a 500 error. Do you know anything about favicons? The error is ...


```

I18n::InvalidLocale 
Devise::SessionsController#new

"en/favicon.ico" is not a valid locale
```

**Comment by ShanaLMoore** [comment]
disregard the above comment. It may not be related. I was testing this on the qa tenant instead of the dc tenant. 

This passes QA! 🎉 



![Image](https://user-images.githubusercontent.com/10081604/201386927-4b85768d-5ee1-4d1c-aefb-f417a8ccecd8.png)


clicking Search: 




![Image](https://user-images.githubusercontent.com/10081604/201390296-977949ea-5351-4fb2-8615-d7bcabb5599d.png)

**Comment by markpbaggett** [comment]
Looks good.  :shipit:
